# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='', verbose_name='Repeatable Image')),
                ('width', models.IntegerField(verbose_name='Width (cm)')),
                ('repeat', models.IntegerField(verbose_name='Pattern repeat (cm)')),
                ('price', models.FloatField(verbose_name='Price per meter')),
            ],
        ),
    ]
