# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-03 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpaper',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='Price per roll'),
            preserve_default=False,
        ),
    ]
