kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: django-postgres-pv-claim
  namespace: lmi
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: django-static-pv-claim
  namespace: lmi
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: django-media-pv-claim
  namespace: lmi
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

